services:

  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    env_file:
      - ./.env
    command: fastapi dev app/main.py --host 0.0.0.0
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - psql-db-data:/var/lib/postgres/data

volumes:
  psql-db-data:
